# Generated by Django 5.1.7 on 2025-03-24 21:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightControl_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_id', models.CharField(max_length=50)),
                ('pilot_id', models.IntegerField()),
                ('message', models.TextField()),
                ('drop_off_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
